// pages/community.vue
<template>
  <div class="wrapper-small">
      <div class=" mt-2 border-b-2 pb-3">
        <h3 class="text-xl md:text-2xl lg:text-3xl text-gray-700 font-semibold">Community</h3>
        <h3 class="text-sm md:text-base text-gray-600 font-semibold my-3">Da quando ho inziato ad essere presente sui social ho avuto modo di conoscere e collaborare con diverse community e voglio dedicare uno spazio per loro.</h3>
      </div>
      <div class="grid grid-cols-4 gap-4">
        <div class="text-center">
          <img src="~/assets/community/vuejsitalia.jpg" class="">
          <p class="text-gray-700 font-bold">VueJsItalia</p>
        </div>
        <div>2</div>
        <div>3</div>
        <div>9</div>
      </div>
  </div>
</template>

<script>
export default {

}
</script>

<style>
  
    .credit-item{
        @apply text-lg mb-5 text-gray-800 font-semibold;
    }

    .credit-link{
        @apply text-primary;
    }
</style>

// src/components/Community/Community.jsx
import { COMMUNITY } from './Community.const'
import PropTypes from 'prop-types'

const ImgWithFallback = ({
  src,
  fallback,
  type = 'image/webp',
  alt,
  ...delegated
}) => {
  return (
    <picture>
      <source srcSet={src} type={type} />
      <img src={fallback} {...delegated} alt={alt} width="200px" />
    </picture>
  )
}

ImgWithFallback.propTypes = {
  src: PropTypes.string,
  fallback: PropTypes.string,
  type: PropTypes.string,
  alt: PropTypes.string,
}

const Community = () => {
  return (
    <div id="community" className="mt-20">
      <h2>Community</h2>
      <p>
        Da quando ho inziato ad essere presente sui social ho avuto modo di
        conoscere e collaborare con diverse community e voglio dedicare uno
        spazio per loro.
      </p>
      <div className="flex flex-wrap flex-row">
        {COMMUNITY.map((e, index) => (
          <div
            className="w-full md:w-1/5 p-4 flex flex-col items-center justify-center"
            key={index}
          >
            <a
              href={e.link}
              className="flex flex-col items-center justify-center"
              target="_blank"
              rel="noreferrer"
            >
              <ImgWithFallback
                src={`./assets/community/${e.fileCompr}`}
                fallback={`./assets/community/${e.file}`}
                alt={e.name + 'logo'}
              />
              <p className="underline underline-offset-2 text-sm font-bold">
                {e.name}
              </p>
            </a>
          </div>
        ))}
      </div>
    </div>
  )
}

export default Community
